---
- name: make deps
  command: chdir={{switchboard_root}} make PROFILE={{switchboard_profile}} deps
  tags:
    - deps
    - build

- name: make app
  command: chdir={{switchboard_root}} make PROFILE={{switchboard_profile}} app
  tags:
    - app
    - build

- name: switchboard release
  command: chdir={{switchboard_root}} make PROFILE={{switchboard_profile}} rel
  tags:
    - rel
    - build