# Site settings
title: Switchboard
email: switchboard@librelist.com
description: "Switchboard handles the boilerplate of server-side email processing, leaving you free to create the logic."
baseurl: ""
url: "http://switchboard.spatch.co"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments

# Set default layouts, allowing external files to be included
defaults:
  -
    scope:
      path: "guide"
    values:
      layout: "guide"
